spring:
  application:
    name: part-time-backend

  datasource:
    url: jdbc:mysql://localhost:3306/store?createDatabaseIfNotExist=true
    username: root
    password:

  jpa:
    show-sql: true

  cloud:
    azure:
      storage:
        account-name: ${AZURE_STORAGE_ACCOUNT_NAME:YOUR_ACCOUNT_NAME}
        account-key: ${AZURE_STORAGE_ACCOUNT_KEY:YOUR_ACCOUNT_KEY}

  ai:
    model:
      chat: ollama
    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama3.1:8b
      embedding:
        enabled: true
        options:
          model: llama3.1:8b

server:
  port: 8080

