spring:
  application:
    name: part-time-backend
  mail:
    host: smtp.gmail.com
    port: 587
    username: jayanianuththara10@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:mysql://localhost:3306/store?createDatabaseIfNotExist=true
    username: root
    password:

  jpa:
    show-sql: true

  cloud:
    azure:
      storage:
        account-name: ${AZURE_STORAGE_ACCOUNT_NAME:YOUR_ACCOUNT_NAME}
        account-key: ${AZURE_STORAGE_ACCOUNT_KEY:YOUR_ACCOUNT_KEY}

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.4
          max-tokens: 150
      embedding:
        options:
          model: text-embedding-3-small

  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 3600 # 1 hr
    refreshTokenExpiration: 604800 # 7d

server:
  port: 8080



